### ISSUE TITLE
Pacman Cache can be a problem.

### ISSUE THREAD

**Issue by Nechochwen-D** [Chloe-ko/SteamDeckPersistentRootFs#1]
You may want to suggest changing the Pacman cache from,
`CacheDir = /var/cache/pacman/pkg/`
to,
`CacheDir = /tmp/cache/pacman/pkg/`
as 250MiB is not nearly enough to even install some programs.

**Comment by Chloe-ko** [comment]
Thanks, I added the suggestion to the readme.
